project:
  type: default
  output-dir: outputs/timetable

format: 
  html: 
    toc: false
    execute:
      eval: true
      echo: false
      warning: false
      message: false
    lang: en-GB
    css: styles.css